#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4F{1,0,16.12,0
#
TM4C_Receiver.xem4f: package/cfg/TM4C_Receiver.xem4f.mak

clean::
	-$(RM) package/cfg/TM4C_Receiver.xem4f.mak
